# Generated by Django 3.0.2 on 2020-01-14 22:33

from django.db import migrations, models
import django.db.models.deletion
import restaurants.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=5, max_digits=7, validators=[restaurants.validators.validate_lat])),
                ('lon', models.DecimalField(decimal_places=5, max_digits=8, validators=[restaurants.validators.validate_lon])),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=5, max_digits=7, validators=[restaurants.validators.validate_lat])),
                ('lon', models.DecimalField(decimal_places=5, max_digits=8, validators=[restaurants.validators.validate_lon])),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('is_approved', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.City')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
