version: '3'
services:
    db:
        image: "postgres:12"
        env_file:
            - .env
        environment:
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_DB: "${POSTGRES_DB}"
        command: -p ${POSTGRES_PORT}

    backend:
        build: ./backend/
        working_dir: /backend/
        env_file:
            - .env
        volumes:
            - ./backend:/backend
        links:
            - db
        environment:
            DEV: 0
            SECRET_KEY: "${SECRET_KEY}"

    frontend:
        build:
            context: .
            dockerfile: ./frontend/prod.Dockerfile
        volumes:
            - ./frontend:/frontend
            - frontend-static:/usr/src/app/dist/gdzieJedzonko

    nginx:
        image: nginx:1.17.4-alpine
        ports:
            - ${PORT:-80}:80  # default port for all
        volumes:
            - ./nginx/nginx-proxy-prod.conf:/etc/nginx/conf.d/default.conf:ro
            - frontend-static:/var/www/frontend/
        depends_on:
          - backend
          - frontend

volumes:
    frontend-static:
