version: '3'
services:
    db:
        image: "postgres:12"
        env_file:
            - .env
        environment:
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_DB: "${POSTGRES_DB}"
        command: -p ${POSTGRES_PORT}

    backend:
        build: ./backend/
        working_dir: /backend/
        env_file:
            - .env
        ports:
            - 8000:8000  # For extra dev debug
        volumes:
            - ./backend:/backend
        links:
            - db
        environment:
            DEV: 1
            SECRET_KEY: "${SECRET_KEY}"

    
    frontend:
        build:
            context: .
            dockerfile: ./frontend/dev.Dockerfile
        ports:
            - 4200:4200    # For extra dev debug
            - 49153:49153  # Required to HOT-RELOAD
        volumes:
            - ./frontend:/frontend
            - ./frontend/src:/usr/src/app/src/  # Required to HOT-RELOAD

    nginx:
        image: nginx:1.17.4-alpine
        ports:
            - 80:80  # default port for all
        volumes:
            - ./nginx/nginx-proxy-dev.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
          - backend
          - frontend
